codecov:
  token: a9edee92-3ce3-4223-a3ee-f7ccd9e0111e
  notify:
    require_ci_to_pass: no 

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
